spring:

### 데이터베이스 ###
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    url: jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_DELAY=-1

### 파일 ###
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 105MB

### JPA 설정 ###
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
    properties:
      hibernate:
#        format_sql: true
#        show_sql: true

### Thymeleaf 설정 ###
  thymeleaf:
    check-template-location: false

### 메시징 - RabbitMQ (주석처리: 로컬에 RabbitMQ 없을 경우) ###
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest
#    virtual-host: /

### MyBatis ###
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml

### JWT 설정 ###
jwt:
  secret: mySecretKeyForJwtTokenGenerationAndValidationPurposeOnly123456789
  expiration: 86400000  # 24시간 (24 * 60 * 60 * 1000 밀리초)

### Swagger/OpenAPI 설정 ###
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

### 캐시 설정 ###
my:
  cache:
    type: caffeine

